###POST   /api/v1/books
##GET    /api/v1/books/:42
##PUT    /api/v1/books/:id
##DELETE /api/v1/books/:id
##GET    /api/v1/books/:id/reviews
##GET    /api/v1/books/:id/average-rating

##Краткий список результатов
##GET — Извлекает данные без побочных эффектов.
##POST — Отправляет данные для создания нового ресурса.
##PUT — Заменяет весь существующий ресурс.
##PATCH — Применяет частичные изменения к ресурсу.
##DELETE — Удаляет указанный ресурс.
##HEAD — Идентичен GET, но возвращает только заголовки.





##
##GET http://localhost:3000/ping HTTP/1.1









##POST   http://localhost:3000/api/v1/books WORKIN
##GET    http://localhost:3000/api/v1/books WORKIN
##GET    http://localhost:3000/api/v1/books/999 WORKIN
##PUT    http://localhost:3000/api/v1/books/52 

##DELETE http://localhost:3000/api/v1/books/52 WORKIN


##POST   http://localhost:3000/api/v1/books/52/reviews WORKIN
##GET    http://localhost:3000/api/v1/books/52/reviews
##GET    http://localhost:3000/api/v1/books/52/average-rating